# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Giorgio Angelotti
"""Minimal types for the compiled extension; the typed public API is the brook package."""
from typing import Any

class CudaError(RuntimeError): ...

class Context:
    def __init__(self, device: int = 0) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class DeviceArray:
    def __getattr__(self, name: str) -> Any: ...

def __getattr__(name: str) -> Any: ...
